# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba8b3bc05181450e8c6373a39ba7fce3d5b7afb33498014b685e70dc7b95f011dd5adf07ff00072670ae61f07d8f00e646c13da72800539dc8e33ce60d244c2a

test:
  secret_key_base: 3ec6f748654dc24586d3bc22f9bc882b30bc2a802e019e286042a29f147e89a5c833c9172b9c3f11452b1a3866a054a30a1638e786b3e50843b689b2fc891416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
